# Generated by Django 4.2.20 on 2026-03-06 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="employer",
            options={
                "verbose_name": "Prestataire",
                "verbose_name_plural": "Prestataires",
            },
        ),
        migrations.AlterField(
            model_name="appointment",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="client_appointments",
                to="appointments.client",
            ),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="employer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="employer_appointments",
                to="appointments.employer",
            ),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="feedback",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="payment_method",
            field=models.CharField(
                choices=[("carte", "Carte Dahabiya"), ("especes", "Espèces")],
                default="especes",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="rating",
            field=models.IntegerField(
                blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True
            ),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="service",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="service_appointments",
                to="appointments.service",
            ),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="status",
            field=models.CharField(
                choices=[
                    ("en_attente", "En attente"),
                    ("accepté", "Accepté"),
                    ("refusé", "Refusé"),
                    ("en_cours", "En cours"),
                    ("terminé", "Terminé"),
                    ("annulé", "Annulé"),
                ],
                default="en_attente",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="total_amount",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="client",
            name="phone",
            field=models.CharField(
                blank=True, max_length=15, null=True, verbose_name="Téléphone"
            ),
        ),
        migrations.AlterField(
            model_name="employer",
            name="email",
            field=models.EmailField(
                max_length=254, unique=True, verbose_name="Email du prestataire"
            ),
        ),
        migrations.AlterField(
            model_name="employer",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Prestataire actif"),
        ),
        migrations.AlterField(
            model_name="employer",
            name="is_verified",
            field=models.BooleanField(
                default=False, verbose_name="Prestataire vérifié"
            ),
        ),
        migrations.AlterField(
            model_name="employer",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Nom du prestataire"),
        ),
        migrations.AlterField(
            model_name="employer",
            name="phone",
            field=models.CharField(
                blank=True, max_length=15, null=True, verbose_name="Téléphone"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
