# Generated by Django 5.1.5 on 2025-01-21 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Client', 'verbose_name_plural': 'Clients'},
        ),
        migrations.AlterModelOptions(
            name='employer',
            options={'verbose_name': 'Employeur', 'verbose_name_plural': 'Employeurs'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Service', 'verbose_name_plural': 'Services'},
        ),
        migrations.AlterField(
            model_name='appointment',
            name='client',
            field=models.ForeignKey(help_text='Sélectionnez le client associé au rendez-vous.', on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='appointments.client', verbose_name='Client'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateTimeField(help_text="Entrez la date et l'heure du rendez-vous.", verbose_name='Date du rendez-vous'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='description',
            field=models.TextField(blank=True, help_text='Entrez une description pour le rendez-vous (facultatif).', null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='employer',
            field=models.ForeignKey(help_text="Sélectionnez l'employeur associé au rendez-vous.", on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='appointments.employer', verbose_name='Employeur'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='feedback',
            field=models.TextField(blank=True, help_text='Feedback ou retour sur le rendez-vous (facultatif).', null=True, verbose_name='Feedback'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='payment_method',
            field=models.CharField(choices=[('carte', 'Carte Dahabiya'), ('especes', 'Espèces')], default='especes', help_text='Sélectionnez le mode de paiement.', max_length=20, verbose_name='Mode de paiement'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='rating',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], help_text='Évaluation du service (1 à 5 étoiles).', null=True, verbose_name='Évaluation'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('en attente', 'En attente'), ('terminé', 'Terminé')], default='en attente', help_text='Statut actuel du rendez-vous.', max_length=20, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Entrez le montant total du rendez-vous.', max_digits=10, verbose_name='Montant total'),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(help_text='Entrez une adresse email unique.', max_length=254, unique=True, verbose_name='Email du client'),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(help_text='Entrez le nom complet du client.', max_length=100, verbose_name='Nom du client'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(help_text='Entrez un numéro de téléphone.', max_length=15, verbose_name='Numéro de téléphone'),
        ),
        migrations.AlterField(
            model_name='employer',
            name='email',
            field=models.EmailField(help_text='Entrez une adresse email unique.', max_length=254, unique=True, verbose_name="Email de l'employeur"),
        ),
        migrations.AlterField(
            model_name='employer',
            name='name',
            field=models.CharField(help_text="Entrez le nom complet de l'employeur.", max_length=255, verbose_name="Nom de l'employeur"),
        ),
        migrations.AlterField(
            model_name='employer',
            name='phone',
            field=models.CharField(blank=True, help_text='Entrez un numéro de téléphone (facultatif).', max_length=15, null=True, verbose_name='Numéro de téléphone'),
        ),
        migrations.AlterField(
            model_name='employer',
            name='service',
            field=models.ForeignKey(blank=True, help_text='Sélectionnez le service fourni par cet employeur.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='appointments.service', verbose_name='Service associé'),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(help_text='Donnez une brève description du service.', verbose_name='Description du service'),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(help_text='Entrez le nom du service (ex. Electricité, Plomberie).', max_length=100, verbose_name='Nom du service'),
        ),
    ]
