# Generated by Django 4.2.20 on 2026-03-06 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "appointments",
            "0002_alter_employer_options_alter_appointment_client_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="client_appointments",
                to="appointments.client",
                verbose_name="Client",
            ),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="employer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="employer_appointments",
                to="appointments.employer",
                verbose_name="Prestataire",
            ),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="feedback",
            field=models.TextField(blank=True, null=True, verbose_name="Feedback"),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="payment_method",
            field=models.CharField(
                choices=[("carte", "Carte Dahabiya"), ("especes", "Espèces")],
                default="especes",
                max_length=20,
                verbose_name="Mode de paiement",
            ),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="rating",
            field=models.IntegerField(
                blank=True,
                choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)],
                null=True,
                verbose_name="Évaluation",
            ),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="service",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="service_appointments",
                to="appointments.service",
                verbose_name="Service",
            ),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="status",
            field=models.CharField(
                choices=[
                    ("en_attente", "En attente"),
                    ("accepté", "Accepté"),
                    ("refusé", "Refusé"),
                    ("en_cours", "En cours"),
                    ("terminé", "Terminé"),
                    ("annulé", "Annulé"),
                ],
                default="en_attente",
                max_length=20,
                verbose_name="Statut",
            ),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="total_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=10,
                verbose_name="Montant total",
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="phone",
            field=models.CharField(
                default="", max_length=15, verbose_name="Numéro de téléphone"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="employer",
            name="phone",
            field=models.CharField(
                blank=True, max_length=15, null=True, verbose_name="Numéro de téléphone"
            ),
        ),
    ]
