# Generated by Django 5.1.5 on 2025-01-22 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_alter_client_options_alter_employer_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='service',
            field=models.ForeignKey(blank=True, help_text='Sélectionnez le service pour ce rendez-vous.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='appointments.service', verbose_name='Service'),
        ),
    ]
