# Generated by Django 4.2.20 on 2025-04-27 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_alter_appointment_client_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='estimated_duration',
            field=models.IntegerField(blank=True, help_text='Durée estimée en minutes', null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email du client'),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nom du client'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(max_length=15, verbose_name='Numéro de téléphone'),
        ),
        migrations.AlterField(
            model_name='employer',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name="Email de l'employeur"),
        ),
        migrations.AlterField(
            model_name='employer',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Employeur actif'),
        ),
        migrations.AlterField(
            model_name='employer',
            name='name',
            field=models.CharField(max_length=255, verbose_name="Nom de l'employeur"),
        ),
        migrations.AlterField(
            model_name='employer',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Numéro de téléphone'),
        ),
    ]
