# Generated by Django 4.2.20 on 2026-04-19 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0003_alter_appointment_client_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="phone",
            field=models.CharField(
                blank=True,
                default="",
                max_length=15,
                verbose_name="Numéro de téléphone",
            ),
        ),
        migrations.AlterField(
            model_name="employer",
            name="phone",
            field=models.CharField(
                blank=True,
                default="",
                max_length=15,
                verbose_name="Numéro de téléphone",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="address",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(blank=True, default="", max_length=15),
        ),
    ]
