# Generated by Django 4.2.20 on 2026-04-20 17:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0004_alter_client_phone_alter_employer_phone_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="address",
            field=models.TextField(blank=True, default="", verbose_name="Adresse"),
        ),
        migrations.AddField(
            model_name="service",
            name="category",
            field=models.CharField(
                blank=True, default="", max_length=120, verbose_name="Catégorie"
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="city",
            field=models.CharField(
                blank=True, default="", max_length=120, verbose_name="Ville"
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="duration",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Durée estimée en minutes",
                null=True,
                verbose_name="Durée",
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="location",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="Localisation"
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Prix",
            ),
        ),
    ]
