# Generated by Django 4.2.20 on 2026-05-23 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0005_service_address_service_category_service_city_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="service",
            name="address",
        ),
        migrations.RemoveField(
            model_name="service",
            name="category",
        ),
        migrations.RemoveField(
            model_name="service",
            name="city",
        ),
        migrations.RemoveField(
            model_name="service",
            name="duration",
        ),
        migrations.RemoveField(
            model_name="service",
            name="location",
        ),
        migrations.RemoveField(
            model_name="service",
            name="price",
        ),
    ]
