# Generated by Django 4.2.20 on 2026-05-23 20:45

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        (
            "appointments",
            "0006_remove_service_address_remove_service_category_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=160)),
                ("email", models.EmailField(db_index=True, max_length=254)),
                ("subject", models.CharField(max_length=200)),
                ("message", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ouvert", "Ouvert"),
                            ("en_cours", "En cours"),
                            ("ferme", "Fermé"),
                        ],
                        default="ouvert",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Demande de contact",
                "verbose_name_plural": "Demandes de contact",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Conversation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Conversation",
                "verbose_name_plural": "Conversations",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="FavoriteEmployer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Prestataire favori",
                "verbose_name_plural": "Prestataires favoris",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FavoriteService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Service favori",
                "verbose_name_plural": "Services favoris",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sender_type",
                    models.CharField(
                        choices=[("client", "Client"), ("prestataire", "Prestataire")],
                        max_length=20,
                    ),
                ),
                ("content", models.TextField()),
                ("is_read", models.BooleanField(default=False)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Message",
                "verbose_name_plural": "Messages",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ]
                    ),
                ),
                ("comment", models.TextField(blank=True, default="")),
                ("is_published", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Avis",
                "verbose_name_plural": "Avis",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AlterModelOptions(
            name="availability",
            options={
                "ordering": ["employer_id", "day_of_week", "start_time"],
                "verbose_name": "Disponibilité",
                "verbose_name_plural": "Disponibilités",
            },
        ),
        migrations.AlterModelOptions(
            name="client",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Client",
                "verbose_name_plural": "Clients",
            },
        ),
        migrations.AlterModelOptions(
            name="employer",
            options={
                "ordering": ["-is_verified", "-average_rating", "name"],
                "verbose_name": "Prestataire",
                "verbose_name_plural": "Prestataires",
            },
        ),
        migrations.AlterModelOptions(
            name="notification",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
            },
        ),
        migrations.AlterModelOptions(
            name="service",
            options={
                "ordering": ["name"],
                "verbose_name": "Service",
                "verbose_name_plural": "Services",
            },
        ),
        migrations.AddField(
            model_name="appointment",
            name="cancel_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="appointment",
            name="canceled_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="appointment",
            name="canceled_by",
            field=models.CharField(
                blank=True,
                choices=[
                    ("client", "Client"),
                    ("prestataire", "Prestataire"),
                    ("systeme", "Système"),
                ],
                default="",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="client",
            name="city",
            field=models.CharField(
                blank=True, default="", max_length=120, verbose_name="Ville"
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="client",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="employer",
            name="address",
            field=models.TextField(blank=True, default="", verbose_name="Adresse pro"),
        ),
        migrations.AddField(
            model_name="employer",
            name="city",
            field=models.CharField(
                blank=True, default="", max_length=120, verbose_name="Ville"
            ),
        ),
        migrations.AddField(
            model_name="employer",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="service",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="service",
            name="slug",
            field=models.SlugField(blank=True, max_length=140, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="service",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="description",
            field=models.TextField(blank=True, default="", verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="feedback",
            field=models.TextField(blank=True, default="", verbose_name="Feedback"),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="location",
            field=models.TextField(
                blank=True, default="", help_text="Adresse du rendez-vous"
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="address",
            field=models.TextField(blank=True, default="", verbose_name="Adresse"),
        ),
        migrations.AlterField(
            model_name="client",
            name="email",
            field=models.EmailField(
                db_index=True,
                max_length=254,
                unique=True,
                verbose_name="Email du client",
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="name",
            field=models.CharField(max_length=160, verbose_name="Nom du client"),
        ),
        migrations.AlterField(
            model_name="client",
            name="phone",
            field=models.CharField(
                blank=True,
                default="",
                max_length=20,
                verbose_name="Numéro de téléphone",
            ),
        ),
        migrations.AlterField(
            model_name="employer",
            name="description",
            field=models.TextField(blank=True, default="", verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="employer",
            name="email",
            field=models.EmailField(
                db_index=True,
                max_length=254,
                unique=True,
                verbose_name="Email du prestataire",
            ),
        ),
        migrations.AlterField(
            model_name="employer",
            name="phone",
            field=models.CharField(
                blank=True,
                default="",
                max_length=20,
                verbose_name="Numéro de téléphone",
            ),
        ),
        migrations.AlterField(
            model_name="employer",
            name="total_reviews",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="service",
            name="description",
            field=models.TextField(
                blank=True, default="", verbose_name="Description du service"
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="icon",
            field=models.CharField(
                blank=True, default="fas fa-tools", max_length=80, verbose_name="Icône"
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="name",
            field=models.CharField(
                max_length=120, unique=True, verbose_name="Nom du service"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="address",
            field=models.TextField(blank=True, default="", verbose_name="Adresse"),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, verbose_name="email address"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(
                blank=True, default="", max_length=20, verbose_name="Téléphone"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="profile_picture",
            field=models.ImageField(
                blank=True, null=True, upload_to="users/profile_pics/"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("client", "Client"), ("employer", "Prestataire")],
                default="client",
                help_text="Compatibilité legacy : un utilisateur peut aussi avoir les 2 profils.",
                max_length=20,
                verbose_name="Rôle principal",
            ),
        ),
        migrations.AddIndex(
            model_name="appointment",
            index=models.Index(fields=["status"], name="appointment_status_8fe9d7_idx"),
        ),
        migrations.AddIndex(
            model_name="appointment",
            index=models.Index(fields=["date"], name="appointment_date_85c852_idx"),
        ),
        migrations.AddIndex(
            model_name="appointment",
            index=models.Index(
                fields=["client", "date"], name="appointment_client__ab13e2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="appointment",
            index=models.Index(
                fields=["employer", "date"], name="appointment_employe_ab87b6_idx"
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="appointment",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="structured_review",
                to="appointments.appointment",
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="appointments.client",
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="employer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="appointments.employer",
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="conversation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to="appointments.conversation",
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="sender_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sent_messages",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="favoriteservice",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="favorite_services",
                to="appointments.client",
            ),
        ),
        migrations.AddField(
            model_name="favoriteservice",
            name="service",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="favorited_by_clients",
                to="appointments.service",
            ),
        ),
        migrations.AddField(
            model_name="favoriteemployer",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="favorite_employers",
                to="appointments.client",
            ),
        ),
        migrations.AddField(
            model_name="favoriteemployer",
            name="employer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="favorited_by_clients",
                to="appointments.employer",
            ),
        ),
        migrations.AddField(
            model_name="conversation",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="conversations",
                to="appointments.client",
            ),
        ),
        migrations.AddField(
            model_name="conversation",
            name="employer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="conversations",
                to="appointments.employer",
            ),
        ),
        migrations.AddField(
            model_name="contactrequest",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="contact_requests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="review",
            constraint=models.CheckConstraint(
                check=models.Q(("rating__gte", 1), ("rating__lte", 5)),
                name="review_rating_between_1_5",
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["conversation", "created_at"],
                name="appointment_convers_59e04a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["is_read"], name="appointment_is_read_66abde_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="favoriteservice",
            unique_together={("client", "service")},
        ),
        migrations.AlterUniqueTogether(
            name="favoriteemployer",
            unique_together={("client", "employer")},
        ),
        migrations.AlterUniqueTogether(
            name="conversation",
            unique_together={("client", "employer")},
        ),
    ]
